### YamlMime:ManagedReference
items:
- uid: Virtufin.WebSocketManager.Configuration
  commentId: N:Virtufin.WebSocketManager.Configuration
  id: Configuration
  parent: Virtufin.WebSocketManager
  children:
  - Virtufin.WebSocketManager.Configuration.ConnectionEvents
  - Virtufin.WebSocketManager.Configuration.DaprConstants
  - Virtufin.WebSocketManager.Configuration.InfraEvents
  - Virtufin.WebSocketManager.Configuration.InstanceHeartbeatOptions
  - Virtufin.WebSocketManager.Configuration.PortConstants
  - Virtufin.WebSocketManager.Configuration.TimeoutConstants
  - Virtufin.WebSocketManager.Configuration.Topics
  langs:
  - csharp
  - vb
  name: Virtufin.WebSocketManager.Configuration
  nameWithType: Virtufin.WebSocketManager.Configuration
  fullName: Virtufin.WebSocketManager.Configuration
  type: Namespace
  assemblies:
  - Virtufin.WebSocketManager
references:
- uid: Virtufin.WebSocketManager.Configuration.ConnectionEvents
  commentId: T:Virtufin.WebSocketManager.Configuration.ConnectionEvents
  href: Virtufin.WebSocketManager.Configuration.ConnectionEvents.html
  name: ConnectionEvents
  nameWithType: ConnectionEvents
  fullName: Virtufin.WebSocketManager.Configuration.ConnectionEvents
- uid: Virtufin.WebSocketManager.Configuration.DaprConstants
  commentId: T:Virtufin.WebSocketManager.Configuration.DaprConstants
  href: Virtufin.WebSocketManager.Configuration.DaprConstants.html
  name: DaprConstants
  nameWithType: DaprConstants
  fullName: Virtufin.WebSocketManager.Configuration.DaprConstants
- uid: Virtufin.WebSocketManager.Configuration.InfraEvents
  commentId: T:Virtufin.WebSocketManager.Configuration.InfraEvents
  href: Virtufin.WebSocketManager.Configuration.InfraEvents.html
  name: InfraEvents
  nameWithType: InfraEvents
  fullName: Virtufin.WebSocketManager.Configuration.InfraEvents
- uid: Virtufin.WebSocketManager.Configuration.InstanceHeartbeatOptions
  commentId: T:Virtufin.WebSocketManager.Configuration.InstanceHeartbeatOptions
  parent: Virtufin.WebSocketManager.Configuration
  href: Virtufin.WebSocketManager.Configuration.InstanceHeartbeatOptions.html
  name: InstanceHeartbeatOptions
  nameWithType: InstanceHeartbeatOptions
  fullName: Virtufin.WebSocketManager.Configuration.InstanceHeartbeatOptions
- uid: Virtufin.WebSocketManager.Configuration.PortConstants
  commentId: T:Virtufin.WebSocketManager.Configuration.PortConstants
  href: Virtufin.WebSocketManager.Configuration.PortConstants.html
  name: PortConstants
  nameWithType: PortConstants
  fullName: Virtufin.WebSocketManager.Configuration.PortConstants
- uid: Virtufin.WebSocketManager.Configuration.TimeoutConstants
  commentId: T:Virtufin.WebSocketManager.Configuration.TimeoutConstants
  href: Virtufin.WebSocketManager.Configuration.TimeoutConstants.html
  name: TimeoutConstants
  nameWithType: TimeoutConstants
  fullName: Virtufin.WebSocketManager.Configuration.TimeoutConstants
- uid: Virtufin.WebSocketManager.Configuration.Topics
  commentId: T:Virtufin.WebSocketManager.Configuration.Topics
  href: Virtufin.WebSocketManager.Configuration.Topics.html
  name: Topics
  nameWithType: Topics
  fullName: Virtufin.WebSocketManager.Configuration.Topics
- uid: Virtufin.WebSocketManager.Configuration
  commentId: N:Virtufin.WebSocketManager.Configuration
  href: Virtufin.html
  name: Virtufin.WebSocketManager.Configuration
  nameWithType: Virtufin.WebSocketManager.Configuration
  fullName: Virtufin.WebSocketManager.Configuration
  spec.csharp:
  - uid: Virtufin
    name: Virtufin
    href: Virtufin.html
  - name: .
  - uid: Virtufin.WebSocketManager
    name: WebSocketManager
    href: Virtufin.WebSocketManager.html
  - name: .
  - uid: Virtufin.WebSocketManager.Configuration
    name: Configuration
    href: Virtufin.WebSocketManager.Configuration.html
  spec.vb:
  - uid: Virtufin
    name: Virtufin
    href: Virtufin.html
  - name: .
  - uid: Virtufin.WebSocketManager
    name: WebSocketManager
    href: Virtufin.WebSocketManager.html
  - name: .
  - uid: Virtufin.WebSocketManager.Configuration
    name: Configuration
    href: Virtufin.WebSocketManager.Configuration.html
